version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: solare_company_sas
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solare_backend
      MYSQL_USER: solare_user
      MYSQL_PASSWORD: 847417
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  solare-backend:
    build: .
    container_name: solare_backend
    restart: always
    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/solare_backend?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: solare_user
      SPRING_DATASOURCE_PASSWORD: 847417
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect

      WOMPI_ENABLED: "false"
      WOMPI_URL: https://sandbox.wompi.co/v1
      WOMPI_PUBLIC_KEY: fake
      WOMPI_PRIVATE_KEY: fake
    ports:
      - "8080:8080"
volumes:
  mysql_data:
