
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME} #solare_user
    password: ${SPRING_DATASOURCE_PASSWORD} #847417

    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

server:
    port: 8080
